[toolchain]
anchor_version  = "0.31.1"
solana_version  = "2.1.0"

[features]
seeds           = false
skip-lint       = false

[programs.localnet]
vault_key           = "MSL1yHXY3tn1fXBg52v2GgGA2qNuQofBMoehEf8arjw"
guardian_multisig   = "MSLLafYHvuDb1kkukoEijtnERRScQn2n6x7YyH2mMhX"
monasol_protocol    = "MSL3a81xY93z7zzqFEjxh1EyUo2mUJeQ6xc8UAQRba9"

[programs.devnet]
vault_key           = "MSL1yHXY3tn1fXBg52v2GgGA2qNuQofBMoehEf8arjw"
guardian_multisig   = "MSLLafYHvuDb1kkukoEijtnERRScQn2n6x7YyH2mMhX"
monasol_protocol    = "MSL3a81xY93z7zzqFEjxh1EyUo2mUJeQ6xc8UAQRba9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster  = "localnet"
wallet   = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
types = "target/types"
