// =============================================================================
// tests/helpers.ts — MonaSol Protocol test utilities
// =============================================================================
// Shared across all three test files:
//   • PDA derivation (mirrors on-chain seeds exactly)
//   • Keypair / wallet generation helpers
//   • Anchor discriminator computation
//   • Airdrop + balance utilities
//   • Program client construction
//   • Common constants
// =============================================================================

import * as anchor from "@coral-xyz/anchor";
import { Program, AnchorProvider, BN }  from "@coral-xyz/anchor";
import {
  Keypair,
  PublicKey,
  SystemProgram,
  LAMPORTS_PER_SOL,
  Connection,
}                                        from "@solana/web3.js";
import { createHash }                    from "crypto";

// -----------------------------------------------------------------------------
// IDL imports — generated by `anchor build`
// These paths resolve after first build on server
// -----------------------------------------------------------------------------
import { VaultKey }          from "../target/types/vault_key";
import { GuardianMultisig }  from "../target/types/guardian_multisig";
import { MonasolProtocol }   from "../target/types/monasol_protocol";

// -----------------------------------------------------------------------------
// Program IDs — must match Anchor.toml after `anchor keys sync`
// -----------------------------------------------------------------------------
export const VAULT_KEY_PROGRAM_ID = new PublicKey(
  "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
);
export const GUARDIAN_MULTISIG_PROGRAM_ID = new PublicKey(
  "4Nd1mBQtrMJVYVfKf2PX8Q7pSe8KBnM23sYs5KGR2ZtG"
);
export const MONASOL_PROTOCOL_PROGRAM_ID = new PublicKey(
  "HEvSKofvBgfaexv23kMabbYqxasxU3mQ4ibBMEmJWHny"
);

// Metaplex Core program ID
export const MPL_CORE_PROGRAM_ID = new PublicKey(
  "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
);

// -----------------------------------------------------------------------------
// Seeds — must match on-chain constants exactly
// -----------------------------------------------------------------------------
export const VAULT_SESSION_SEED    = Buffer.from("vault_session");
export const PROTOCOL_AUTH_SEED    = Buffer.from("protocol_auth");
export const GUARDIAN_SET_SEED     = Buffer.from("guardian_set");
export const SHARD_RECORD_SEED     = Buffer.from("shard_record");
export const APPROVAL_SEED         = Buffer.from("approval");
export const PROTOCOL_STATE_SEED   = Buffer.from("protocol_state");
export const SESSION_RECORD_SEED   = Buffer.from("session_record");
export const ORACLE_VERIFIER_SEED  = Buffer.from("oracle_verifier");

// -----------------------------------------------------------------------------
// PDA derivation
// -----------------------------------------------------------------------------

export function deriveVaultSession(
  renter: PublicKey,
  collection: PublicKey,
  programId = VAULT_KEY_PROGRAM_ID
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [VAULT_SESSION_SEED, renter.toBuffer(), collection.toBuffer()],
    programId
  );
}

export function deriveProtocolAuth(
  programId = VAULT_KEY_PROGRAM_ID
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [PROTOCOL_AUTH_SEED],
    programId
  );
}

export function deriveGuardianSet(
  leaseId: BN,
  programId = GUARDIAN_MULTISIG_PROGRAM_ID
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [GUARDIAN_SET_SEED, leaseId.toArrayLike(Buffer, "le", 8)],
    programId
  );
}

export function deriveShardRecord(
  leaseId: BN,
  shardMember: PublicKey,
  programId = GUARDIAN_MULTISIG_PROGRAM_ID
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [
      SHARD_RECORD_SEED,
      leaseId.toArrayLike(Buffer, "le", 8),
      shardMember.toBuffer(),
    ],
    programId
  );
}

export function deriveApprovalRecord(
  leaseId: BN,
  approver: PublicKey,
  programId = GUARDIAN_MULTISIG_PROGRAM_ID
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [
      APPROVAL_SEED,
      leaseId.toArrayLike(Buffer, "le", 8),
      approver.toBuffer(),
    ],
    programId
  );
}

export function deriveProtocolState(
  programId = MONASOL_PROTOCOL_PROGRAM_ID
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [PROTOCOL_STATE_SEED],
    programId
  );
}

export function deriveSessionRecord(
  leaseId: BN,
  programId = MONASOL_PROTOCOL_PROGRAM_ID
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [SESSION_RECORD_SEED, leaseId.toArrayLike(Buffer, "le", 8)],
    programId
  );
}

export function deriveOracleVerifier(
  programId = MONASOL_PROTOCOL_PROGRAM_ID
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [ORACLE_VERIFIER_SEED],
    programId
  );
}

// -----------------------------------------------------------------------------
// Discriminator computation
// Anchor discriminator = sha256("global:<instruction_name>")[0..8]
// Use this to verify and populate the CPI byte arrays in monasol_protocol.
// -----------------------------------------------------------------------------

export function computeDiscriminator(instructionName: string): Buffer {
  const hash = createHash("sha256")
    .update(`global:${instructionName}`)
    .digest();
  return hash.subarray(0, 8);
}

/**
 * Print all 4 discriminators needed by monasol_protocol CPI builders.
 * Call this once after first build to get the real values.
 *
 * Usage in test:
 *   printCpiDiscriminators();
 */
export function printCpiDiscriminators(): void {
  const instructions = [
    "thaw_key",
    "move_out",
    "mark_settled",
    "close_guardian_set",
  ];

  console.log("\n=== CPI Discriminators for monasol_protocol ===");
  for (const ix of instructions) {
    const disc = computeDiscriminator(ix);
    const bytes = Array.from(disc)
      .map((b) => `0x${b.toString(16).padStart(2, "0")}`)
      .join(", ");
    console.log(`${ix.padEnd(24)} → [${bytes}]`);
  }
  console.log("================================================\n");
}

// -----------------------------------------------------------------------------
// Keypair helpers
// -----------------------------------------------------------------------------

/** Generate N fresh keypairs. */
export function makeKeypairs(n: number): Keypair[] {
  return Array.from({ length: n }, () => Keypair.generate());
}

/**
 * Build a standard 5-member guardian array.
 * Returns { shardMembers: [kp0, kp1], approvers: [kp2, kp3, kp4] }
 * and a flat `members` array in the correct positional order.
 */
export function makeGuardianCouncil(): {
  shardMembers: [Keypair, Keypair];
  approvers:    [Keypair, Keypair, Keypair];
  members:      PublicKey[];
} {
  const [s0, s1, a0, a1, a2] = makeKeypairs(5);
  return {
    shardMembers: [s0, s1],
    approvers:    [a0, a1, a2],
    members:      [s0.publicKey, s1.publicKey, a0.publicKey, a1.publicKey, a2.publicKey],
  };
}

/**
 * Build a mock 32-byte Monad transaction hash for testing.
 * In prod this comes from the Monad RPC.
 */
export function mockMonadTxHash(seed = "test"): number[] {
  const hash = createHash("sha256").update(seed).digest();
  return Array.from(hash);
}

/**
 * Build a mock shard commitment:
 *   SHA-256(fragment_bytes || lease_id_le_bytes)
 * Mirrors the off-chain shard commitment construction.
 */
export function mockShardCommitment(
  fragmentSeed: string,
  leaseId: BN
): number[] {
  const fragment = Buffer.from(fragmentSeed);
  const leaseIdBytes = leaseId.toArrayLike(Buffer, "le", 8);
  const hash = createHash("sha256")
    .update(Buffer.concat([fragment, leaseIdBytes]))
    .digest();
  return Array.from(hash);
}

// -----------------------------------------------------------------------------
// Airdrop helpers
// -----------------------------------------------------------------------------

export async function airdrop(
  connection: Connection,
  pubkey: PublicKey,
  sol = 10
): Promise<void> {
  const sig = await connection.requestAirdrop(
    pubkey,
    sol * LAMPORTS_PER_SOL
  );
  await connection.confirmTransaction(sig, "confirmed");
}

export async function airdropMany(
  connection: Connection,
  keypairs: Keypair[],
  sol = 2
): Promise<void> {
  await Promise.all(keypairs.map((kp) => airdrop(connection, kp.publicKey, sol)));
}

// -----------------------------------------------------------------------------
// Program client construction
// -----------------------------------------------------------------------------

export function getVaultKeyProgram(
  provider: AnchorProvider,
  idl: VaultKey
): Program<VaultKey> {
  return new Program(idl, provider);
}

export function getGuardianMultisigProgram(
  provider: AnchorProvider,
  idl: GuardianMultisig
): Program<GuardianMultisig> {
  return new Program(idl, provider);
}

export function getMonasolProtocolProgram(
  provider: AnchorProvider,
  idl: MonasolProtocol
): Program<MonasolProtocol> {
  return new Program(idl, provider);
}

// -----------------------------------------------------------------------------
// Balance assertion helper
// -----------------------------------------------------------------------------

export async function assertBalanceIncreased(
  connection: Connection,
  pubkey: PublicKey,
  before: number,
  label = ""
): Promise<void> {
  const after = await connection.getBalance(pubkey);
  if (after <= before) {
    throw new Error(
      `${label} balance did not increase: before=${before} after=${after}`
    );
  }
}

// -----------------------------------------------------------------------------
// Common test lease ID — increment per test suite to avoid PDA collisions
// -----------------------------------------------------------------------------
export const TEST_LEASE_ID_BASE = new BN(1_000_000);
