uploads = []

[[generated]]
id = "OyEMtNq5C2BTkQWCVafyX"
uri = "file://artifacts/neighborhood-watch/assets/images/icon.png"
type = "image"
title = "neighborhood watch shield icon"

[[outputs]]
id = "mSF7Eal_zRBmEkHQVzvQT"
uri = "file://.local/reports/monasol-test-and-lint-report.zip"
type = "unspecified"
title = "MonaSol Protocol — Test & Code Quality Report"
