[package]
name    = "guardian_multisig"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name       = "guardian_multisig"

[dependencies]
anchor-lang    = { workspace = true }

[dev-dependencies]
anchor-client = { version = "0.31.1", features = ["mock"] }
