// =============================================================================
// src/lib/oracle-client.ts
// =============================================================================
// Anchor program clients and typed instruction builders for the three
// MonaSol Solana programs.
//
// Provides:
//   • getPrograms()             — lazy-initialised Anchor program clients
//   • PDA derivation functions  — mirrors on-chain seeds exactly
//   • Instruction builders      — one per oracle-triggered instruction
//   • sendAndConfirm()          — shared transaction submission with retry
//
// All PDA seeds must stay in sync with the on-chain constants:
//   vault_key:          VAULT_SESSION_SEED, PROTOCOL_AUTH_SEED
//   guardian_multisig:  GUARDIAN_SET_SEED
//   monasol_protocol:   PROTOCOL_STATE_SEED, SESSION_RECORD_SEED,
//                       ORACLE_VERIFIER_SEED
// =============================================================================

import {
  Connection,
  Keypair,
  PublicKey,
  SystemProgram,
  Transaction,
  sendAndConfirmTransaction,
  TransactionSignature,
} from "@solana/web3.js";
import {
  AnchorProvider,
  Program,
  BN,
  Wallet,
  setProvider,
} from "@coral-xyz/anchor";
import { logger } from "./logger";
import {
  connection,
  oracleKeypair,
  VAULT_KEY_PROGRAM_ID,
  GUARDIAN_MULTISIG_PROGRAM_ID,
  MONASOL_PROTOCOL_PROGRAM_ID,
  MPL_CORE_PROGRAM_ID,
} from "./solana";

// IDL imports — generated by `anchor build`
import type { VaultKey }         from "../../target/types/vault_key";
import type { GuardianMultisig } from "../../target/types/guardian_multisig";
import type { MonasolProtocol }  from "../../target/types/monasol_protocol";
import vaultKeyIdl         from "../../target/idl/vault_key.json" assert { type: "json" };
import guardianMultisigIdl from "../../target/idl/guardian_multisig.json" assert { type: "json" };
import monasolProtocolIdl  from "../../target/idl/monasol_protocol.json" assert { type: "json" };

// -----------------------------------------------------------------------------
// Seeds — must match on-chain constants exactly
// -----------------------------------------------------------------------------

const VAULT_SESSION_SEED   = Buffer.from("vault_session");
const PROTOCOL_AUTH_SEED   = Buffer.from("protocol_auth");
const GUARDIAN_SET_SEED    = Buffer.from("guardian_set");
const PROTOCOL_STATE_SEED  = Buffer.from("protocol_state");
const SESSION_RECORD_SEED  = Buffer.from("session_record");
const ORACLE_VERIFIER_SEED = Buffer.from("oracle_verifier");

// -----------------------------------------------------------------------------
// Provider — oracle keypair as the wallet signer
// -----------------------------------------------------------------------------

function makeProvider(): AnchorProvider {
  const wallet = new Wallet(oracleKeypair);
  return new AnchorProvider(connection, wallet, {
    commitment: "confirmed",
    preflightCommitment: "confirmed",
  });
}

// -----------------------------------------------------------------------------
// Lazy program clients — initialised once on first call
// -----------------------------------------------------------------------------

let _provider:  AnchorProvider | null = null;
let _vaultKey:  Program<VaultKey> | null = null;
let _guardian:  Program<GuardianMultisig> | null = null;
let _monasol:   Program<MonasolProtocol> | null = null;

export function getPrograms(): {
  provider:   AnchorProvider;
  vaultKey:   Program<VaultKey>;
  guardian:   Program<GuardianMultisig>;
  monasol:    Program<MonasolProtocol>;
} {
  if (!_provider) {
    _provider = makeProvider();
    setProvider(_provider);
  }
  if (!_vaultKey) {
    _vaultKey = new Program(
      vaultKeyIdl as unknown as VaultKey,
      _provider
    );
  }
  if (!_guardian) {
    _guardian = new Program(
      guardianMultisigIdl as unknown as GuardianMultisig,
      _provider
    );
  }
  if (!_monasol) {
    _monasol = new Program(
      monasolProtocolIdl as unknown as MonasolProtocol,
      _provider
    );
  }

  return {
    provider: _provider,
    vaultKey: _vaultKey,
    guardian: _guardian,
    monasol:  _monasol,
  };
}

// -----------------------------------------------------------------------------
// PDA derivation
// -----------------------------------------------------------------------------

export function deriveVaultSession(
  renter: PublicKey,
  collection: PublicKey
): PublicKey {
  const [pda] = PublicKey.findProgramAddressSync(
    [VAULT_SESSION_SEED, renter.toBuffer(), collection.toBuffer()],
    VAULT_KEY_PROGRAM_ID
  );
  return pda;
}

export function deriveProtocolAuth(): PublicKey {
  const [pda] = PublicKey.findProgramAddressSync(
    [PROTOCOL_AUTH_SEED],
    VAULT_KEY_PROGRAM_ID
  );
  return pda;
}

export function deriveGuardianSet(leaseId: BN): PublicKey {
  const [pda] = PublicKey.findProgramAddressSync(
    [GUARDIAN_SET_SEED, leaseId.toArrayLike(Buffer, "le", 8)],
    GUARDIAN_MULTISIG_PROGRAM_ID
  );
  return pda;
}

export function deriveProtocolState(): PublicKey {
  const [pda] = PublicKey.findProgramAddressSync(
    [PROTOCOL_STATE_SEED],
    MONASOL_PROTOCOL_PROGRAM_ID
  );
  return pda;
}

export function deriveSessionRecord(leaseId: BN): PublicKey {
  const [pda] = PublicKey.findProgramAddressSync(
    [SESSION_RECORD_SEED, leaseId.toArrayLike(Buffer, "le", 8)],
    MONASOL_PROTOCOL_PROGRAM_ID
  );
  return pda;
}

export function deriveOracleVerifier(): PublicKey {
  const [pda] = PublicKey.findProgramAddressSync(
    [ORACLE_VERIFIER_SEED],
    MONASOL_PROTOCOL_PROGRAM_ID
  );
  return pda;
}

// -----------------------------------------------------------------------------
// Shared transaction helper
// Wraps sendAndConfirmTransaction with logging and retry on blockhash expiry.
// -----------------------------------------------------------------------------

const MAX_RETRIES = 3;

export async function sendAndConfirm(
  tx: Transaction,
  signers: Keypair[],
  label: string
): Promise<TransactionSignature> {
  for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
    try {
      const sig = await sendAndConfirmTransaction(connection, tx, signers, {
        commitment: "confirmed",
        preflightCommitment: "confirmed",
      });

      logger.info({ sig, label }, "Solana transaction confirmed");
      return sig;
    } catch (err: any) {
      const isBlockhashExpiry =
        err?.message?.includes("Blockhash not found") ||
        err?.message?.includes("block height exceeded");

      if (isBlockhashExpiry && attempt < MAX_RETRIES) {
        logger.warn(
          { label, attempt },
          "Blockhash expired — retrying transaction"
        );
        continue;
      }

      logger.error({ err, label }, "Solana transaction failed");
      throw err;
    }
  }

  throw new Error(`${label}: exceeded ${MAX_RETRIES} retry attempts`);
}

// -----------------------------------------------------------------------------
// Instruction builders
// -----------------------------------------------------------------------------

export interface RegisterSessionParams {
  leaseId:      BN;
  renter:       PublicKey;
  vaultSession: PublicKey;
  guardianSet:  PublicKey;
  asset:        PublicKey;
  collection:   PublicKey;
  monadTxRef:   number[];  // 32-byte Monad tx hash as number[]
}

/**
 * Build and send monasol_protocol::register_session.
 * Signed by the oracle keypair.
 */
export async function registerSession(
  params: RegisterSessionParams
): Promise<TransactionSignature> {
  const { monasol } = getPrograms();

  const protocolState  = deriveProtocolState();
  const oracleVerifier = deriveOracleVerifier();
  const sessionRecord  = deriveSessionRecord(params.leaseId);

  const sig = await monasol.methods
    .registerSession({
      leaseId:      params.leaseId,
      renter:       params.renter,
      vaultSession: params.vaultSession,
      guardianSet:  params.guardianSet,
      asset:        params.asset,
      collection:   params.collection,
      monadTxRef:   params.monadTxRef,
    })
    .accountsStrict({
      oracle:        oracleKeypair.publicKey,
      payer:         oracleKeypair.publicKey,
      protocolState,
      oracleVerifier,
      sessionRecord,
      systemProgram: SystemProgram.programId,
    })
    .signers([oracleKeypair])
    .rpc();

  logger.info(
    {
      sig,
      leaseId:   params.leaseId.toString(),
      renter:    params.renter.toBase58(),
      sessionRecord: sessionRecord.toBase58(),
    },
    "oracle: register_session confirmed"
  );

  return sig;
}

// -----------------------------------------------------------------------------

export interface ConfirmSettlementParams {
  leaseId:       BN;
  monadTxHash:   number[];  // 32-byte Monad settlement tx hash
  guardianSet:   PublicKey;
  asset:         PublicKey;
  collection:    PublicKey;
}

/**
 * Build and send monasol_protocol::confirm_settlement.
 * Signed by the oracle keypair.
 * Triggers CPIs: vault_key::thaw_key + guardian_multisig::mark_settled.
 */
export async function confirmSettlement(
  params: ConfirmSettlementParams
): Promise<TransactionSignature> {
  const { monasol } = getPrograms();

  const protocolState  = deriveProtocolState();
  const oracleVerifier = deriveOracleVerifier();
  const sessionRecord  = deriveSessionRecord(params.leaseId);
  const protocolAuth   = deriveProtocolAuth();

  const sig = await monasol.methods
    .confirmSettlement(params.monadTxHash)
    .accountsStrict({
      oracle:                   oracleKeypair.publicKey,
      payer:                    oracleKeypair.publicKey,
      protocolState,
      oracleVerifier,
      sessionRecord,
      protocolAuth,
      guardianSet:              params.guardianSet,
      asset:                    params.asset,
      collection:               params.collection,
      vaultKeyProgram:          VAULT_KEY_PROGRAM_ID,
      guardianMultisigProgram:  GUARDIAN_MULTISIG_PROGRAM_ID,
      mplCoreProgram:           MPL_CORE_PROGRAM_ID,
      systemProgram:            SystemProgram.programId,
    })
    .signers([oracleKeypair])
    .rpc();

  logger.info(
    {
      sig,
      leaseId:      params.leaseId.toString(),
      sessionRecord: sessionRecord.toBase58(),
    },
    "oracle: confirm_settlement confirmed"
  );

  return sig;
}

// -----------------------------------------------------------------------------

export interface FinalizeReleaseParams {
  leaseId:      BN;
  operatorKeypair: Keypair;   // operator signs finalize_release
  vaultSession: PublicKey;
  guardianSet:  PublicKey;
  asset:        PublicKey;
  collection:   PublicKey;
}

/**
 * Build and send monasol_protocol::finalize_release.
 * Signed by the operator keypair (not the oracle).
 * Triggers CPIs: vault_key::move_out + guardian_multisig::close_guardian_set.
 */
export async function finalizeRelease(
  params: FinalizeReleaseParams
): Promise<TransactionSignature> {
  const { monasol } = getPrograms();

  const protocolState = deriveProtocolState();
  const sessionRecord = deriveSessionRecord(params.leaseId);
  const protocolAuth  = deriveProtocolAuth();

  // finalize_release requires both operator (authority) and payer
  // The operator keypair must be the registered protocol authority
  const sig = await monasol.methods
    .finalizeRelease()
    .accountsStrict({
      operator:                params.operatorKeypair.publicKey,
      payer:                   params.operatorKeypair.publicKey,
      protocolState,
      authority:               params.operatorKeypair.publicKey,
      sessionRecord,
      protocolAuth,
      vaultSession:            params.vaultSession,
      asset:                   params.asset,
      collection:              params.collection,
      guardianSet:             params.guardianSet,
      vaultKeyProgram:         VAULT_KEY_PROGRAM_ID,
      guardianMultisigProgram: GUARDIAN_MULTISIG_PROGRAM_ID,
      mplCoreProgram:          MPL_CORE_PROGRAM_ID,
      systemProgram:           SystemProgram.programId,
    })
    .signers([params.operatorKeypair])
    .rpc();

  logger.info(
    {
      sig,
      leaseId:      params.leaseId.toString(),
      sessionRecord: sessionRecord.toBase58(),
    },
    "oracle: finalize_release confirmed"
  );

  return sig;
}

// -----------------------------------------------------------------------------
// Account fetchers — for route response hydration
// -----------------------------------------------------------------------------

export async function fetchSessionRecord(leaseId: BN) {
  const { monasol } = getPrograms();
  const sessionRecord = deriveSessionRecord(leaseId);

  try {
    return await monasol.account.sessionRecord.fetch(sessionRecord);
  } catch {
    return null;
  }
}

export async function fetchGuardianSet(leaseId: BN) {
  const { guardian } = getPrograms();
  const guardianSet = deriveGuardianSet(leaseId);

  try {
    return await guardian.account.guardianSet.fetch(guardianSet);
  } catch {
    return null;
  }
}

export async function fetchVaultSession(
  renter: PublicKey,
  collection: PublicKey
) {
  const { vaultKey } = getPrograms();
  const vaultSession = deriveVaultSession(renter, collection);

  try {
    return await vaultKey.account.vaultSession.fetch(vaultSession);
  } catch {
    return null;
  }
}
