import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Shield, Search, ExternalLink, Lock, Key } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

export function VaultExplorer() {
  const [searchId, setSearchId] = useState("");
  const [accessKey, setAccessKey] = useState("");
  const [isSearching, setIsSearching] = useState(false);
  const [vaultData, setVaultData] = useState<any>(null);
  const [error, setError] = useState("");

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    if (!searchId) return;

    setIsSearching(true);
    setError("");
    setVaultData(null);

    // Simulate network delay and permission check
    setTimeout(() => {
      setIsSearching(false);
      
      // Mock validation logic: Requires both ID 42 and a valid access key
      if (searchId === "42" || searchId === "#42") {
        if (accessKey === "GRANT-X79") {
          setVaultData({
            id: "0442",
            status: "Locked & Verified",
            token: "USDC",
            amount: "100,000.00",
            network: "Monad",
            lastUpdated: "Just now",
            isVerified: true
          });
        } else {
          setError("Access Denied: You need a valid Access Key generated by the vault owner to view these contents.");
        }
      } else {
        setError("Vault not found. Check the NFT ID.");
      }
    }, 1500);
  };

  return (
    <div className="glass-panel rounded-2xl p-6 sm:p-8 relative overflow-hidden mt-8 border border-white/5">
      {/* Background Decor */}
      <div className="absolute top-0 left-0 w-64 h-64 bg-solana-green/5 blur-[80px] rounded-full pointer-events-none -translate-y-1/2 -translate-x-1/2" />

      <div className="flex items-center gap-3 mb-6 relative z-10">
        <div className="p-3 rounded-xl bg-solana-green/20 text-solana-green shadow-[0_0_15px_rgba(20,241,149,0.2)]">
          <Search className="h-6 w-6" />
        </div>
        <div>
          <div className="flex items-center gap-2">
            <h2 className="font-display text-2xl font-bold text-white">Private Explorer</h2>
            <span className="px-2 py-0.5 rounded text-xs font-bold bg-white/10 text-white/60 border border-white/5 uppercase">
              On-Chain Opacity
            </span>
          </div>
          <p className="text-sm text-gray-400">Verify Monad assets securely with owner permission</p>
        </div>
      </div>

      <form onSubmit={handleSearch} className="space-y-4 relative z-10">
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label className="text-xs uppercase tracking-wider text-gray-400">NFT ID</Label>
            <div className="relative">
              <Input
                placeholder="e.g. 42"
                value={searchId}
                onChange={(e) => setSearchId(e.target.value)}
                className="bg-black/20 border-white/10 h-12 pl-10 font-mono text-sm focus-visible:ring-solana-green"
              />
              <div className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500 font-bold">
                #
              </div>
            </div>
          </div>
          
          <div className="space-y-2">
            <Label className="text-xs uppercase tracking-wider text-gray-400 flex items-center justify-between">
              <span>Access Key</span>
              <span className="text-xs text-gray-400">Provided by vault owner</span>
            </Label>
            <div className="relative">
              <Input
                type="password"
                placeholder="Paste access key..."
                value={accessKey}
                onChange={(e) => setAccessKey(e.target.value)}
                className="bg-black/20 border-white/10 h-12 pl-10 font-mono text-sm focus-visible:ring-solana-green"
              />
              <Key className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-500" />
            </div>
          </div>
        </div>

        <Button 
          type="submit" 
          disabled={isSearching || !searchId || !accessKey}
          className="w-full h-12 mt-2 bg-solana-green hover:bg-solana-green/90 text-black font-bold shadow-[0_0_15px_-3px_rgba(20,241,149,0.4)]"
        >
          {isSearching ? "Decrypting Verification Proof..." : "Verify Vault Contents"}
        </Button>
      </form>

      <AnimatePresence mode="wait">
        {error && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            className="mt-6 p-4 rounded-lg bg-red-500/10 border border-red-500/20 flex items-start gap-3"
          >
            <Lock className="h-5 w-5 text-red-400 shrink-0 mt-0.5" />
            <p className="text-sm text-red-400 leading-relaxed font-medium">{error}</p>
          </motion.div>
        )}

        {vaultData && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="mt-6 space-y-4"
          >
            <div className="flex items-center justify-between p-4 rounded-xl bg-white/5 border border-white/10">
              <div className="flex items-center gap-3">
                <Shield className="h-5 w-5 text-solana-green" />
                <span className="text-sm font-medium text-white">Cryptographic Proof Verified for NFT #{vaultData.id}</span>
              </div>
              <span className="px-2 py-1 rounded text-xs font-bold bg-solana-green/20 text-solana-green border border-solana-green/30">
                {vaultData.status}
              </span>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="p-4 rounded-xl bg-black/40 border border-white/5 relative overflow-hidden">
                <div className="absolute top-0 right-0 p-2 opacity-10">
                  <Lock className="h-12 w-12 text-white" />
                </div>
                <Label className="text-xs uppercase tracking-wider text-gray-500 mb-1 block relative z-10">Asset</Label>
                <p className="font-mono text-lg text-white font-bold relative z-10">{vaultData.token}</p>
              </div>
              <div className="p-4 rounded-xl bg-black/40 border border-white/5 relative overflow-hidden">
                 <div className="absolute top-0 right-0 w-16 h-16 bg-solana-green/5 blur-xl rounded-full" />
                <Label className="text-xs uppercase tracking-wider text-gray-500 mb-1 block relative z-10">Amount Locked</Label>
                <p className="font-mono text-lg text-solana-green font-bold relative z-10">{vaultData.amount}</p>
              </div>
              <div className="p-4 rounded-xl bg-black/40 border border-white/5">
                <Label className="text-xs uppercase tracking-wider text-gray-500 mb-1 block">Network</Label>
                <div className="flex items-center gap-2">
                  <div className="h-2 w-2 rounded-full bg-monad-purple shadow-[0_0_8px_rgba(130,71,229,0.8)]" />
                  <p className="font-mono text-sm text-gray-300">{vaultData.network}</p>
                </div>
              </div>
              <div className="p-4 rounded-xl bg-black/40 border border-white/5">
                <Label className="text-xs uppercase tracking-wider text-gray-500 mb-1 block">Last Audit</Label>
                <div className="flex items-center gap-2">
                  <p className="font-mono text-sm text-gray-300">{vaultData.lastUpdated}</p>
                  <ExternalLink className="h-3 w-3 text-gray-500" />
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}